### ISSUE TITLE
gem doesn't explicitly depend on rest-client

### ISSUE THREAD

**Issue by cptaffe** [jeremyevans/kaeruera#2]
```
kaeruera-0.2.0/lib/kaeruera/reporter.rb:1:in `require': cannot load such file -- rest-client (LoadError)
```
Should this be an explicit dependency of the KaeruEra gem?

**Comment by jeremyevans** [comment]
You can use the database reporter without rest-client, but that's probably a less common use of the gem.  I think having the gem depend on rest-client makes sense.  I'll try to make the changes and push out a new gem this week.

**Comment by jeremyevans** [comment]
After looking at the current dependencies of rest-client, I think it is too overweight for kaeruera's needs.  When I originally worked on kaeruera, rest-client only depended on mime-types.  The current version of rest-client now has 7 depedencies, including one that is a C extension (unf_ext).  I'll try to find time soon to rewrite the reporter to use net/http instead of rest-client and release a new version, but it may be a few weeks.

**Comment by jeremyevans** [comment]
I've pushed a commit that uses net/http directly instead of rest-client.  Can you please test this and let me know if it works for you?  If so, I can push out a new gem release soon.

**Comment by cptaffe** [comment]
`report` catches this error:
> use_ssl value changed, but session already started (IOError)

docs 
> Turn on/off SSL. This flag must be set before starting session. If you change use_ssl value after session started, a Net::HTTP object raises IOError.

Possible solutions
```ruby
http = Net::HTTP.new
http.use_ssl = true if url.scheme == 'https'
res = http.start{|http| http.request(req)}

# or
res = Net::HTTP.start(url.host, url.port, :use_ssl=>url.scheme == 'https') do |http|
  http.request(req)
end
```

**Comment by jeremyevans** [comment]
Thanks for the quick feedback, I've pushed 3f230647b096d49dbc61881be1a5cbc487988bca which should fix this.  Can you please retest with that commit?

**Comment by cptaffe** [comment]
No problem. That commit works for me, both `Reporter` and `AsycReporter` report errors to the server.

**Comment by jeremyevans** [comment]
Perfect, thanks again for the quick testing.  As you can see, the tests don't currently test SSL use. :)  I'll push out a 0.3.0 gem shortly.

**Comment by jeremyevans** [comment]
0.3.0 gem released: https://rubygems.org/gems/kaeruera
