### ISSUE TITLE
Unable to login to demo site

### ISSUE THREAD

**Issue by abhijitnandy** [jeremyevans/kaeruera#3]
Hi Jeremy,

the login to the demo site with the credentials `demo/demo` doesn't seem to work. It's expecting an `@` in the email.

I tried `demo@email.com` and `demo@demo.com`

**Comment by jeremyevans** [comment]
Thanks for the report. This is a bug caused by using a newer version of Rodauth that uses email input type by default.  I'll fix it shortly.

**Comment by jeremyevans** [comment]
OK, this should be working now.  Thanks again for the report!

**Comment by abhijitnandy** [comment]
> OK, this should be working now. Thanks again for the report!

Thanks a lot for that quick response!
